//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Data_model
{
    using System;
    
    public enum PaymentMethods : int
    {
        Cash = 0,
        Bank = 1,
        card = 2
    }
}
